// デモ用モックデータ
import { Post, User, Notification } from "../types";

const users: User[] = [
  {
    id: "1",
    username: "sakura_dev",
    displayName: "さくら",
    avatar: "",
    bio: "フロントエンドエンジニア / React大好き",
    followersCount: 1234,
    followingCount: 567,
    createdAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "2",
    username: "taro_design",
    displayName: "太郎デザイン",
    avatar: "",
    bio: "UIデザイナー。美しいインターフェースを追求中。",
    followersCount: 892,
    followingCount: 345,
    createdAt: "2024-02-20T00:00:00Z",
  },
  {
    id: "3",
    username: "yuki_music",
    displayName: "ゆき",
    avatar: "",
    bio: "音楽とプログラミングが趣味です♪",
    followersCount: 2456,
    followingCount: 123,
    createdAt: "2023-11-01T00:00:00Z",
  },
  {
    id: "4",
    username: "ken_gamer",
    displayName: "けんじ",
    avatar: "",
    bio: "ゲーム実況者 / 毎日配信中！",
    followersCount: 5678,
    followingCount: 890,
    createdAt: "2023-06-10T00:00:00Z",
  },
  {
    id: "5",
    username: "mika_food",
    displayName: "みか",
    avatar: "",
    bio: "料理研究家。今日もおいしいものを探求中！",
    followersCount: 3456,
    followingCount: 234,
    createdAt: "2024-03-05T00:00:00Z",
  },
];

export const mockPosts: Post[] = [
  {
    id: "p1",
    userId: "1",
    user: users[0],
    content: "React Nativeでアプリ開発はじめました！Expoがめちゃくちゃ便利で驚いています。ホットリロードが最高すぎる。",
    likesCount: 42,
    repliesCount: 5,
    repostsCount: 12,
    isLiked: false,
    isReposted: false,
    createdAt: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: "p2",
    userId: "2",
    user: users[1],
    content: "新しいUIデザインのトレンド、グラスモーフィズムがまた流行り始めてる気がする。みなさんはどう思います？",
    likesCount: 88,
    repliesCount: 23,
    repostsCount: 31,
    isLiked: true,
    isReposted: false,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "p3",
    userId: "3",
    user: users[2],
    content: "今日のBGMはLo-fi Hip Hopで作業中。プログラミングとの相性抜群だよね。おすすめのプレイリストあったら教えて！",
    likesCount: 156,
    repliesCount: 34,
    repostsCount: 22,
    isLiked: false,
    isReposted: true,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "p4",
    userId: "4",
    user: users[3],
    content: "今日の配信、視聴者1000人突破！みんなありがとう！明日もゲーム配信するからぜひ来てね。",
    likesCount: 423,
    repliesCount: 67,
    repostsCount: 89,
    isLiked: false,
    isReposted: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "p5",
    userId: "5",
    user: users[4],
    content: "今日のレシピ：簡単チーズリゾット。バターで玉ねぎを炒めて、お米を加えて、白ワインとブイヨンで煮込むだけ。最後にパルメザンチーズをたっぷり！",
    likesCount: 234,
    repliesCount: 45,
    repostsCount: 78,
    isLiked: true,
    isReposted: false,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: "p6",
    userId: "1",
    user: users[0],
    content: "TypeScriptの型パズル、解けた時の快感がすごい。今日はConditional Typesをマスターした。",
    likesCount: 67,
    repliesCount: 8,
    repostsCount: 15,
    isLiked: false,
    isReposted: false,
    createdAt: new Date(Date.now() - 28800000).toISOString(),
  },
  {
    id: "p7",
    userId: "3",
    user: users[2],
    content: "週末ライブ終わった！200人も来てくれて感動。次回は3月に予定してるから、またお知らせするね。",
    likesCount: 567,
    repliesCount: 89,
    repostsCount: 123,
    isLiked: false,
    isReposted: false,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "like",
    fromUser: users[1],
    postId: "p1",
    createdAt: new Date(Date.now() - 600000).toISOString(),
    read: false,
  },
  {
    id: "n2",
    type: "follow",
    fromUser: users[2],
    createdAt: new Date(Date.now() - 1200000).toISOString(),
    read: false,
  },
  {
    id: "n3",
    type: "reply",
    fromUser: users[3],
    postId: "p2",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    read: true,
  },
  {
    id: "n4",
    type: "repost",
    fromUser: users[4],
    postId: "p3",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    read: true,
  },
  {
    id: "n5",
    type: "like",
    fromUser: users[0],
    postId: "p5",
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    read: true,
  },
];
